baseURL = "https://www.ramune-diary.com/"
languageCode = "ja-jp"
title = "ラムネの日々"
theme = "ananke"
canonifyURLs = true

[params]
  mainSections = ["posts"]
  background_color_class = "bg-light-pink"
  text_color_class = "dark-gray"
  description = "オフィス猫ラムネの可愛い日常を写真で綴るブログ。毎日のお昼寝、探検、おやつの時間など、愛らしい猫の日々をお楽しみください。"
  favicon = "/favicon.ico"
  custom_css = []
  
[params.ananke]
  show_recent_posts = true

[params.ananke.social.share]
icons = true
sharetext = true
networks = ["x-twitter"]
  
paginate = 30

# SEO Settings
enableRobotsTXT = true
enableGitInfo = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Related Content
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  
  [[related.indices]]
    name = "tags"
    weight = 100
    
  [[related.indices]]
    name = "date"
    weight = 10
