baseURL = "https://luckofwise.github.io/cat-blog/"
languageCode = "ja-jp"
title = "ラムネの日々"
theme = "ananke"
canonifyURLs = true

[params]
  mainSections = ["posts"]
  
[params.ananke]
  show_recent_posts = true
  
paginate = 10
